### ISSUE TITLE
tell me

### ISSUE THREAD

**Issue by FJlashe** [spyoungtech/helldivers2-macros#21]
tell me how to make it so that when you press one button, for example, he himself presses Ctrl and executes the stratagem and then releases LCtrl

**Comment by spyoungtech** [comment]
I'm not sure if I fully understand the question. The hotkey configuration works the same [as in AutoHotkey](https://www.autohotkey.com/docs/v2/Hotkeys.htm). This macro software will only input the direction inputs for the specified stratagem. It will not send other inputs (like ctrl).

So, you define a hotkey to trigger a specific stratagem, as described in the readme. You press that hotkey, then press and hold LCtrl (the default key binding to bring up the stratagem input menu in game), after a short delay, the inputs will be sent.

**Comment by spyoungtech** [comment]
I'm going to close this since it has been a while. If you still have a question, please feel free to open a new issue.
