### ISSUE TITLE
where can i chage the stratagem menu key?

### ISSUE THREAD

**Issue by kohyzsc123** [spyoungtech/helldivers2-macros#27]
thanks for your work
i changed stratagem menu key to "Q"
where can  i change the default key in source code?

**Comment by spyoungtech** [comment]
The macros of this program do not press the menu key for you. So, there shouldn't be any changes needed to the program itself. Users are expected to hold down the menu key manually, as described in the README, in relevant part:

> When you trigger one of your configured hotkeys, a short delay (hotkey_start_delay) will occur -- enough time for you to make sure you have your stratagem menu up -- and the program will enter the WASD inputs for the associated stratagem.
