### ISSUE TITLE
tomllib error when running after PIP install method

### ISSUE THREAD

**Issue by lowfuel** [spyoungtech/helldivers2-macros#9]
I tried the instructions using the PIP method (as I do python development), but I get this error when I try to run "python -m hd2_macros":

`ModuleNotFoundError: No module named 'tomllib'`

**Comment by spyoungtech** [comment]
[tomllib](https://docs.python.org/3/library/tomllib.html) is part of the standard library and is available in Python 3.11 and newer. So, for now, this package requires that you use Python 3.11 or newer.

**Comment by lowfuel** [comment]
Ahh, okay thanks

**Comment by spyoungtech** [comment]
No problem :)

If you have any issues when using Python3.11+ feel free to open a new issue
